repositories:
  - name: Org
    id: organization
  - name: Java
    id: lioncore-java
  - name: MPS
    id: lioncore-mps
  - name: OpenAPI
    id: lioncore-openapi
  - name: TypeScript
    id: lioncore-typescript

serializations:
  - path: lioncore-java/core/src/test/resources/serialization/lioncore.json
    kind: m3
    repo: Java
  - path: lioncore-typescript/models/meta/lioncore.json
    kind: m3
    repo: TypeScript

schemas:
  - path: lioncore-typescript/schemas/lioncore.serialization.schema.json
    kind: m3

