repositories:
  - name: Org
    id: organization
  - name: Java
    id: lionweb-java
  - name: MPS
    id: lionweb-mps
  - name: OpenAPI
    id: lioncore-openapi
  - name: TypeScript
    id: lionweb-typescript

serializations:
  - path: lionweb-java/core/src/test/resources/serialization/lioncore.json
    kind: m3
    repo: Java
  - path: lionweb-typescript/packages/artifacts/chunks/languages/lioncore.json
    kind: m3
    repo: TypeScript

schemas:
  - path: lionweb-typescript/packages/artifacts/schemas/lioncore.serialization.schema.json
    kind: m3

