name: LionWeb integration tests

on: [push, workflow_dispatch]

env:
  NuGetDirectory: ${{github.workspace}}/nuget

jobs:

  ts-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Download JSON Schemas from specification repository
        run: ./scripts/download-json-schemas.sh

      - name: Validate delta JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: 'schemas/delta.schema.json'
          file: 'delta/**/*.json'

      - name: Validate serialization JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: 'schemas/serialization.schema.json'
          file:
            'testchanges/**/*.json|testset/withoutLanguage/valid/**/*.json|testset/withoutLanguage/valid/**.json|testset/withLanguage/valid/**/*.json|testset/withLanguage/valid/*.json'

      - name: Run clone script
        run: ./scripts/clone-repos.sh
        env:
          LIONWEB_PAT: ${{ secrets.LIONWEB_PAT }}

      - name: Validate LionCore serialized by lionweb-jvm
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: 'schemas/serialization.schema.json'
          file:
            '../repos/lionweb-jvm/core/src/test/resources/serialization/lioncore.json'

      - name: Run integration tests implemented in TS
        run: ./scripts/run-ts-tests.sh

  cs-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build all C# projects
        run: dotnet build --configuration Release ./cs/LionWeb.Integration.WebSocket.Tests/

      - name: Test all C# projects
        run: dotnet test --configuration Release --logger trx ./cs/LionWeb.Integration.WebSocket.Tests/

      - name: Publish C# Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/*.trx
          large_files: "true"
          report_individual_runs: "true"
          report_suite_logs: "any"
          check_run_annotations: all tests, skipped tests
          action_fail: "true"

